#!/bin/bash
# CAWS-MANAGED-HOOK
# hook_pack: claude-code
# hook_pack_version: 11
# caws_min_major: 11
# lineage_refs: 8,16
# do_not_edit_directly: update via `caws init --agent-surface claude-code`
# Shared progressive strike handling for Claude pre-write guard hooks.
#
# STRIKE-STATE KEYING (matches CLAUDE.md "Scope-guard strike state"):
# The counter is keyed by (session_id, checkout-location), NOT session-global.
#   - canonical checkout  -> $CLAUDE_PROJECT_DIR/.claude/logs/guard-strikes-<session>.json
#   - inside a worktree   -> <gitdir>/caws-guard-strikes/guard-strikes-<session>.json
#                            (gitdir = <canonical>/.git/worktrees/<name>, OUTSIDE every
#                             working tree so `git add -A` can never commit it —
#                             CAWS-GUARD-STRIKE-FILE-OUT-OF-TREE-001)
# Strikes therefore do NOT bleed across worktrees: a strike in worktree A does
# not corner an edit in worktree B, and a worktree's count is not visible in the
# canonical .claude/logs file. This per-checkout isolation is intentional —
# cross-worktree strike bleed is a high-severity control-plane collapse risk.
# (If a block says "strike 3" but the canonical .claude/logs
# file shows fewer, you're reading the wrong file: the live count is in your
# current checkout's strike file.)
#
# If you are reading this because a guard blocked you, do not edit this file or
# the generated guard-strikes JSON directly to bypass enforcement. The correct
# recovery paths are:
#   1. Switch into the right CAWS worktree.
#   2. Bring the target file into the active spec's scope.in (if it legitimately
#      belongs there), then ask the user to reset your strikes by running:
#        bash .claude/hooks/reset-strikes.sh --current
#      or the equivalent narrower reset (see --help).
#   3. Ask the user to resolve the conflict explicitly.
# Never edit guard-strikes-*.json files by hand — use reset-strikes.sh so the
# reason is logged to .claude/logs/strike-resets.log.

# This file is SOURCED by scope-guard.sh / worktree-guard.sh. Locate lib/
# relative to THIS file (BASH_SOURCE[0]) so the canonical emit primitives
# are available regardless of the sourcing hook's cwd
# (HOOK-LIB-CONSOLIDATION-001 T3a).
_GUARD_STRIKES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/emit.sh
source "$_GUARD_STRIKES_DIR/lib/emit.sh" 2>/dev/null || true

guard_worktree_state_dir() {
  local cwd_hint="${1:-}"
  local project_dir="${CLAUDE_PROJECT_DIR:-.}"
  local worktree_dir=""

  if [[ -n "$cwd_hint" ]] && [[ "$cwd_hint" =~ ^(.*\/\.caws\/worktrees\/[^/]+)($|/) ]]; then
    worktree_dir="${BASH_REMATCH[1]}"
  fi

  if [[ -z "$worktree_dir" ]] && [[ "$project_dir" =~ ^(.*\/\.caws\/worktrees\/[^/]+)($|/) ]]; then
    worktree_dir="${BASH_REMATCH[1]}"
  fi

  if [[ -z "$worktree_dir" ]] || [[ ! -d "$worktree_dir" ]]; then
    return 1
  fi

  # The strike file must NOT land in the worktree's WORKING TREE. A linked
  # worktree is its own working tree with its own `git status`; a strike file
  # written to `<worktree>/tmp/` shows up as `?? tmp/` and a routine
  # `git add -A` from inside the worktree sweeps it into the feature commit
  # (friction-probe Event 5, CAWS-GUARD-STRIKE-FILE-OUT-OF-TREE-001).
  #
  # Resolve the worktree's GITDIR instead — a linked worktree's `.git` is a
  # FILE whose single line is `gitdir: <canonical>/.git/worktrees/<name>`.
  # Anything under that directory is structurally outside every working tree,
  # so git can never track it. We parse the file directly (no `git` call:
  # these hooks are pure-bash by design and must not shell out).
  local git_pointer="$worktree_dir/.git"
  if [[ -f "$git_pointer" ]]; then
    local gitdir_line
    gitdir_line=$(grep -m1 '^gitdir:' "$git_pointer" 2>/dev/null || true)
    if [[ -n "$gitdir_line" ]]; then
      local gitdir="${gitdir_line#gitdir:}"
      # Trim leading whitespace from `gitdir: <path>`.
      gitdir="${gitdir#"${gitdir%%[![:space:]]*}"}"
      if [[ -n "$gitdir" ]] && [[ -d "$gitdir" ]]; then
        mkdir -p "$gitdir/caws-guard-strikes"
        printf '%s\n' "$gitdir/caws-guard-strikes"
        return 0
      fi
    fi
  fi

  # Could not resolve a gitdir (no .git file, unreadable, or not a linked
  # worktree). Signal the caller to fall back to the canonical .claude/logs
  # location — never fail closed, and never re-introduce the in-tree leak.
  return 1
}

guard_strikes_file() {
  local project_dir="${CLAUDE_PROJECT_DIR:-.}"
  local cwd_hint="${2:-}"
  local log_dir="$project_dir/.claude/logs"
  local session_id="$1"
  local safe_session

  if guard_worktree_state_dir "$cwd_hint" >/dev/null 2>&1; then
    log_dir=$(guard_worktree_state_dir "$cwd_hint")
  else
    mkdir -p "$log_dir"
  fi

  safe_session=$(printf '%s' "$session_id" | tr -c 'A-Za-z0-9._-' '_')
  printf '%s/guard-strikes-%s.json' "$log_dir" "$safe_session"
}

guard_record_strike() {
  local session_id="$1"
  local guard_name="$2"
  local cwd_hint="${3:-}"
  local state_file
  local current_count

  state_file=$(guard_strikes_file "$session_id" "$cwd_hint")
  if [[ ! -f "$state_file" ]]; then
    printf '{}\n' > "$state_file"
  fi

  current_count=$(jq -r --arg guard "$guard_name" '.[$guard] // 0' "$state_file" 2>/dev/null || printf '0')
  if [[ ! "$current_count" =~ ^[0-9]+$ ]]; then
    current_count=0
  fi

  current_count=$((current_count + 1))

  jq --arg guard "$guard_name" --argjson count "$current_count" '.[$guard] = $count' "$state_file" > "$state_file.tmp"
  mv "$state_file.tmp" "$state_file"

  printf '%s\n' "$current_count"
}

# Progressive-strike emitters: thin adapters over the canonical
# lib/emit.sh primitives. The progressive logic (warn -> ask -> block by
# strike count) stays here; the envelope JSON lives only in lib/emit.sh
# (HOOK-LIB-CONSOLIDATION-001 T3a).
guard_emit_warning_allow() { emit_additional_context "$1"; }
guard_emit_permission_ask() { emit_ask "$1"; }
guard_emit_block() { emit_block "$1"; }

guard_enforce_progressive_strikes() {
  local session_id="$1"
  local guard_name="$2"
  local cwd_hint="$3"
  local first_message="$4"
  local second_message="$5"
  local third_message="$6"
  local strike

  strike=$(guard_record_strike "$session_id" "$guard_name" "$cwd_hint")

  case "$strike" in
    1)
      guard_emit_warning_allow "$first_message"
      ;;
    2)
      guard_emit_permission_ask "$second_message"
      ;;
    *)
      guard_emit_block "$third_message"
      ;;
  esac
}
