import { describe, it, expect } from 'vitest';
import fs from 'fs';
import path from 'path';
import {
  Resolver,
  loadResolverDocument,
} from '@/utils/designTokens/utils/resolver-module';
import { extractTokenPaths, type TokenGroup } from '@/utils/designTokens/core';

/**
 * Drift guard for the committed token artifacts. types/designTokens.ts and
 * ui/designTokens/designTokens.json are generated by `tokens:build:full`
 * (compose → types from the DTCG resolver sources), and history shows they
 * rot when a regeneration is skipped or done with the wrong tool. These
 * tests re-derive the expected token set from ui/designTokens/resolver.json
 * in-process — WITHOUT calling composeTokens/generateTokenTypes, which write
 * to hardcoded repo paths — and pin:
 *   - resolver output == committed JSON leaf paths (both directions)
 *   - committed JSON leaf paths == TokenPath union in types/designTokens.ts
 *   - no token path under a top-level "component" namespace (the removed
 *     hand-injected group must not return)
 *   - the composed JSON ends with a trailing newline
 * A failure means the artifacts are stale relative to the token sources:
 * run `npm run tokens:build:full` and review the diff.
 */

const ROOT = path.resolve(__dirname, '..', '..', '..');

function rederiveFromResolver(): Set<string> {
  const resolverDocPath = path.join(
    ROOT,
    'ui',
    'designTokens',
    'resolver.json'
  );
  const resolverDoc = loadResolverDocument(resolverDocPath);
  expect(
    resolverDoc,
    'failed to load ui/designTokens/resolver.json'
  ).toBeTruthy();
  const resolver = new Resolver(
    resolverDoc as NonNullable<typeof resolverDoc>,
    {
      basePath: path.dirname(resolverDocPath),
    }
  );
  // Default context, same as the compose pipeline's resolver branch.
  const result = resolver.resolve({});
  return new Set(extractTokenPaths(result.tokens as TokenGroup));
}

function committedJsonPaths(): Set<string> {
  const file = path.join(ROOT, 'ui', 'designTokens', 'designTokens.json');
  const json = JSON.parse(fs.readFileSync(file, 'utf8'));
  return new Set(extractTokenPaths(json));
}

function typesUnionPaths(): Set<string> {
  const source = fs.readFileSync(
    path.join(ROOT, 'types', 'designTokens.ts'),
    'utf8'
  );
  const unionStart = source.indexOf('export type TokenPath');
  expect(
    unionStart,
    'TokenPath union not found in types/designTokens.ts'
  ).toBeGreaterThan(-1);
  const matches = source
    .slice(unionStart)
    .matchAll(/^\s*\|\s*'([^']+)'\s*;?\s*$/gm);
  return new Set(Array.from(matches, (m) => m[1]));
}

function diffSets(
  expected: Set<string>,
  actual: Set<string>,
  cap = 10
): string {
  const missing = Array.from(expected)
    .filter((p) => !actual.has(p))
    .slice(0, cap);
  const extra = Array.from(actual)
    .filter((p) => !expected.has(p))
    .slice(0, cap);
  const parts: string[] = [];
  if (missing.length > 0)
    parts.push(`missing from actual: ${missing.join(', ')}`);
  if (extra.length > 0) parts.push(`unexpected in actual: ${extra.join(', ')}`);
  return parts.join(' | ') || 'sets equal';
}

describe('committed token artifacts match the token sources', () => {
  it('committed designTokens.json leaf paths equal the resolver-derived token paths', () => {
    const source = rederiveFromResolver();
    const artifact = committedJsonPaths();
    expect(artifact.size, diffSets(source, artifact)).toBe(source.size);
    for (const p of source) {
      expect(artifact.has(p), `resolver path absent from artifact: ${p}`).toBe(
        true
      );
    }
  });

  it('TokenPath union equals the committed artifact paths', () => {
    const artifact = committedJsonPaths();
    const union = typesUnionPaths();
    expect(union.size, diffSets(artifact, union)).toBe(artifact.size);
    for (const p of artifact) {
      expect(
        union.has(p),
        `artifact path absent from TokenPath union: ${p}`
      ).toBe(true);
    }
  });

  it('no token path lives under a top-level component namespace', () => {
    const artifact = committedJsonPaths();
    const offenders = Array.from(artifact).filter((p) =>
      p.startsWith('component.')
    );
    expect(
      offenders,
      'component.* paths must come from modular sources or not at all'
    ).toEqual([]);
  });

  it('the composed JSON ends with a trailing newline', () => {
    const raw = fs.readFileSync(
      path.join(ROOT, 'ui', 'designTokens', 'designTokens.json'),
      'utf8'
    );
    expect(raw.endsWith('\n')).toBe(true);
  });
});
