/* AUTO-GENERATED: Do not edit directly.
 * Source: ui/designTokens/designTokens.json
 */

/**
 * Design Token Paths
 * 
 * Auto-generated TypeScript types for design token paths.
 * Use these types to ensure type safety when referencing tokens.
 */

/**
 * All available design token paths
 */
export type TokenPath =
  | 'color.mode.black'
  | 'color.mode.white'
  | 'color.mode.light'
  | 'color.mode.dark'
  | 'color.mode.transparent'
  | 'color.palette.brand.primary.100'
  | 'color.palette.brand.primary.200'
  | 'color.palette.brand.primary.300'
  | 'color.palette.brand.primary.400'
  | 'color.palette.brand.primary.500'
  | 'color.palette.brand.primary.600'
  | 'color.palette.brand.primary.700'
  | 'color.palette.brand.primary.800'
  | 'color.palette.neutral.100'
  | 'color.palette.neutral.200'
  | 'color.palette.neutral.300'
  | 'color.palette.neutral.400'
  | 'color.palette.neutral.500'
  | 'color.palette.neutral.600'
  | 'color.palette.neutral.700'
  | 'color.palette.neutral.800'
  | 'color.palette.red.100'
  | 'color.palette.red.200'
  | 'color.palette.red.300'
  | 'color.palette.red.400'
  | 'color.palette.red.500'
  | 'color.palette.red.600'
  | 'color.palette.red.700'
  | 'color.palette.red.800'
  | 'color.palette.orange.100'
  | 'color.palette.orange.200'
  | 'color.palette.orange.300'
  | 'color.palette.orange.400'
  | 'color.palette.orange.500'
  | 'color.palette.orange.600'
  | 'color.palette.orange.700'
  | 'color.palette.orange.800'
  | 'color.palette.yellow.100'
  | 'color.palette.yellow.200'
  | 'color.palette.yellow.300'
  | 'color.palette.yellow.400'
  | 'color.palette.yellow.500'
  | 'color.palette.yellow.600'
  | 'color.palette.yellow.700'
  | 'color.palette.yellow.800'
  | 'color.palette.green.100'
  | 'color.palette.green.200'
  | 'color.palette.green.300'
  | 'color.palette.green.400'
  | 'color.palette.green.500'
  | 'color.palette.green.600'
  | 'color.palette.green.700'
  | 'color.palette.green.800'
  | 'color.palette.blue.100'
  | 'color.palette.blue.200'
  | 'color.palette.blue.300'
  | 'color.palette.blue.400'
  | 'color.palette.blue.500'
  | 'color.palette.blue.600'
  | 'color.palette.blue.700'
  | 'color.palette.blue.800'
  | 'color.palette.teal.100'
  | 'color.palette.teal.200'
  | 'color.palette.teal.300'
  | 'color.palette.teal.400'
  | 'color.palette.teal.500'
  | 'color.palette.teal.600'
  | 'color.palette.teal.700'
  | 'color.palette.teal.800'
  | 'color.palette.violet.100'
  | 'color.palette.violet.200'
  | 'color.palette.violet.300'
  | 'color.palette.violet.400'
  | 'color.palette.violet.500'
  | 'color.palette.violet.600'
  | 'color.palette.violet.700'
  | 'color.palette.violet.800'
  | 'color.datavis.viridis.1'
  | 'color.datavis.viridis.2'
  | 'color.datavis.viridis.3'
  | 'color.datavis.viridis.4'
  | 'color.datavis.viridis.5'
  | 'color.datavis.viridis.6'
  | 'color.datavis.viridis.7'
  | 'color.datavis.viridis.8'
  | 'color.datavis.viridis.9'
  | 'color.datavis.viridis.10'
  | 'color.datavis.magma.1'
  | 'color.datavis.magma.2'
  | 'color.datavis.magma.3'
  | 'color.datavis.magma.4'
  | 'color.datavis.magma.5'
  | 'color.datavis.magma.6'
  | 'color.datavis.magma.7'
  | 'color.datavis.magma.8'
  | 'color.datavis.magma.9'
  | 'color.datavis.magma.10'
  | 'color.datavis.plasma.1'
  | 'color.datavis.plasma.2'
  | 'color.datavis.plasma.3'
  | 'color.datavis.plasma.4'
  | 'color.datavis.plasma.5'
  | 'color.datavis.plasma.6'
  | 'color.datavis.plasma.7'
  | 'color.datavis.plasma.8'
  | 'color.datavis.plasma.9'
  | 'color.datavis.plasma.10'
  | 'color.datavis.inferno.1'
  | 'color.datavis.inferno.2'
  | 'color.datavis.inferno.3'
  | 'color.datavis.inferno.4'
  | 'color.datavis.inferno.5'
  | 'color.datavis.inferno.6'
  | 'color.datavis.inferno.7'
  | 'color.datavis.inferno.8'
  | 'color.datavis.inferno.9'
  | 'color.datavis.inferno.10'
  | 'color.datavis.cividis.1'
  | 'color.datavis.cividis.2'
  | 'color.datavis.cividis.3'
  | 'color.datavis.cividis.4'
  | 'color.datavis.cividis.5'
  | 'color.datavis.cividis.6'
  | 'color.datavis.cividis.7'
  | 'color.datavis.cividis.8'
  | 'color.datavis.cividis.9'
  | 'color.datavis.cividis.10'
  | 'color.datavis.categorical.1'
  | 'color.datavis.categorical.2'
  | 'color.datavis.categorical.3'
  | 'color.datavis.categorical.4'
  | 'color.datavis.categorical.5'
  | 'color.datavis.categorical.6'
  | 'color.datavis.categorical.7'
  | 'color.datavis.categorical.8'
  | 'color.datavis.divergent.neg'
  | 'color.datavis.divergent.neu'
  | 'color.datavis.divergent.pos'
  | 'color.gradient.brandPrimary'
  | 'color.gradient.brand.primary'
  | 'color.overlay.scrim'
  | 'color.opacity.50'
  | 'color.selection.background'
  | 'color.selection.foreground'
  | 'color.foreground.primary'
  | 'color.foreground.secondary'
  | 'color.foreground.tertiary'
  | 'color.foreground.accent'
  | 'color.foreground.danger'
  | 'color.foreground.hover'
  | 'color.foreground.link'
  | 'color.foreground.linkHover'
  | 'color.foreground.linkVisited'
  | 'color.foreground.onBrand'
  | 'color.foreground.info'
  | 'color.foreground.success'
  | 'color.foreground.warning'
  | 'color.foreground.onDangerSubtle'
  | 'color.foreground.onInfoSubtle'
  | 'color.foreground.onSuccessSubtle'
  | 'color.foreground.onWarningSubtle'
  | 'color.foreground.highlight'
  | 'color.foreground.disabled'
  | 'color.foreground.placeholder'
  | 'color.foreground.inverse'
  | 'color.background.primary'
  | 'color.background.secondary'
  | 'color.background.tertiary'
  | 'color.background.highlight'
  | 'color.background.accent'
  | 'color.background.hover'
  | 'color.background.dangerStrong'
  | 'color.background.dangerSubtle'
  | 'color.background.elevated'
  | 'color.background.brand'
  | 'color.background.imageOverlay'
  | 'color.background.infoStrong'
  | 'color.background.infoSubtle'
  | 'color.background.successStrong'
  | 'color.background.successSubtle'
  | 'color.background.warningStrong'
  | 'color.background.warningSubtle'
  | 'color.background.active'
  | 'color.background.disabled'
  | 'color.background.placeholder'
  | 'color.background.readOnly'
  | 'color.background.inverse'
  | 'color.border.default'
  | 'color.border.subtle'
  | 'color.border.bold'
  | 'color.border.disabled'
  | 'color.border.light'
  | 'color.border.primary'
  | 'color.border.hover'
  | 'color.border.accent'
  | 'color.border.focus'
  | 'color.border.danger'
  | 'color.border.info'
  | 'color.border.onColor'
  | 'color.border.success'
  | 'color.border.warning'
  | 'color.border.strong'
  | 'color.status.info'
  | 'color.status.success'
  | 'color.status.warning'
  | 'color.status.danger'
  | 'color.status.highlight'
  | 'color.data.trend.default'
  | 'color.data.trend.up'
  | 'color.data.trend.down'
  | 'color.data.trend.neutral'
  | 'color.action.background.primary.default'
  | 'color.action.background.primary.hover'
  | 'color.action.background.primary.active'
  | 'color.action.background.primary.disabled'
  | 'color.action.background.secondary.default'
  | 'color.action.background.secondary.hover'
  | 'color.action.background.secondary.active'
  | 'color.action.background.danger.default'
  | 'color.action.background.danger.hover'
  | 'color.action.background.danger.active'
  | 'color.action.foreground.primary.default'
  | 'color.action.foreground.primary.disabled'
  | 'color.action.foreground.secondary.default'
  | 'color.action.foreground.danger.default'
  | 'color.action.border.primary.default'
  | 'color.action.border.primary.focus'
  | 'color.action.border.secondary.default'
  | 'color.action.border.secondary.hover'
  | 'color.action.border.danger.default'
  | 'color.feedback.background.success.strong'
  | 'color.feedback.background.success.subtle'
  | 'color.feedback.background.warning.strong'
  | 'color.feedback.background.warning.subtle'
  | 'color.feedback.background.danger.strong'
  | 'color.feedback.background.danger.subtle'
  | 'color.feedback.background.info.strong'
  | 'color.feedback.background.info.subtle'
  | 'color.feedback.foreground.success.default'
  | 'color.feedback.foreground.success.onSubtle'
  | 'color.feedback.foreground.warning.default'
  | 'color.feedback.foreground.warning.onSubtle'
  | 'color.feedback.foreground.danger.default'
  | 'color.feedback.foreground.danger.onSubtle'
  | 'color.feedback.foreground.info.default'
  | 'color.feedback.foreground.info.onSubtle'
  | 'color.feedback.border.success'
  | 'color.feedback.border.warning'
  | 'color.feedback.border.danger'
  | 'color.feedback.border.info'
  | 'color.navigation.background.primary'
  | 'color.navigation.background.secondary'
  | 'color.navigation.foreground.primary'
  | 'color.navigation.foreground.secondary'
  | 'color.navigation.foreground.active'
  | 'color.navigation.foreground.hover'
  | 'color.navigation.border.primary'
  | 'color.syntax.plain'
  | 'color.syntax.comment.color'
  | 'color.syntax.keyword'
  | 'color.syntax.definition'
  | 'color.syntax.punctuation'
  | 'color.syntax.property'
  | 'color.syntax.tag'
  | 'color.syntax.static'
  | 'color.syntax.string'
  | 'typography.fontFamily.sans'
  | 'typography.fontFamily.serif'
  | 'typography.fontFamily.mono'
  | 'typography.fontFamily.inter'
  | 'typography.fontFamily.newsreader'
  | 'typography.fontFamily.monaspace'
  | 'typography.weight.thin'
  | 'typography.weight.light'
  | 'typography.weight.regular'
  | 'typography.weight.medium'
  | 'typography.weight.bold'
  | 'typography.weight.black'
  | 'typography.ramp.1'
  | 'typography.ramp.2'
  | 'typography.ramp.3'
  | 'typography.ramp.4'
  | 'typography.ramp.5'
  | 'typography.ramp.6'
  | 'typography.ramp.7'
  | 'typography.ramp.8'
  | 'typography.ramp.9'
  | 'typography.ramp.10'
  | 'typography.ramp.11'
  | 'typography.ramp.12'
  | 'typography.ramp.13'
  | 'typography.ramp.14'
  | 'typography.ramp.15'
  | 'typography.ramp.16'
  | 'typography.lineHeight.tight'
  | 'typography.lineHeight.normal'
  | 'typography.lineHeight.loose'
  | 'typography.lineHeight.body'
  | 'typography.lineHeight.collapse'
  | 'typography.lineHeight.heading'
  | 'typography.letterSpacing.tight'
  | 'typography.letterSpacing.normal'
  | 'typography.letterSpacing.wide'
  | 'typography.features.tabularNums'
  | 'typography.features.liningNums'
  | 'typography.semanticFamily.heading'
  | 'typography.semanticFamily.body'
  | 'typography.semanticFamily.mono'
  | 'typography.semanticFamily.serif'
  | 'typography.body.01'
  | 'typography.body.02'
  | 'typography.body.03'
  | 'typography.body.04'
  | 'typography.body.default.fontFamily'
  | 'typography.body.default.fontWeight'
  | 'typography.body.default.fontSize'
  | 'typography.body.default.lineHeight'
  | 'typography.body.default.letterSpacing'
  | 'typography.body.small.fontFamily'
  | 'typography.body.small.fontWeight'
  | 'typography.body.small.fontSize'
  | 'typography.body.small.lineHeight'
  | 'typography.button.01'
  | 'typography.button.02'
  | 'typography.button.03'
  | 'typography.caption.01'
  | 'typography.caption.02'
  | 'typography.caption.03'
  | 'typography.fontWeight.black'
  | 'typography.fontWeight.bold'
  | 'typography.fontWeight.light'
  | 'typography.fontWeight.medium'
  | 'typography.fontWeight.regular'
  | 'typography.heading.01'
  | 'typography.heading.02'
  | 'typography.heading.03'
  | 'typography.heading.04'
  | 'typography.heading.05'
  | 'typography.heading.06'
  | 'typography.oversize.01'
  | 'typography.oversize.02'
  | 'typography.oversize.03'
  | 'typography.oversize.04'
  | 'typography.meta.caption.fontFamily'
  | 'typography.meta.caption.fontWeight'
  | 'typography.meta.caption.fontSize'
  | 'typography.meta.caption.lineHeight'
  | 'typography.meta.legal.fontFamily'
  | 'typography.meta.legal.fontWeight'
  | 'typography.meta.legal.fontSize'
  | 'typography.meta.legal.lineHeight'
  | 'scale.100'
  | 'scale.110'
  | 'scale.125'
  | 'scale.150'
  | 'scale.175'
  | 'scale.200'
  | 'scale.225'
  | 'scale.250'
  | 'scale.275'
  | 'scale.300'
  | 'scale.base'
  | 'scale.050'
  | 'scale.000'
  | 'spacing.size.10'
  | 'spacing.size.00'
  | 'spacing.size.01'
  | 'spacing.size.02'
  | 'spacing.size.03'
  | 'spacing.size.04'
  | 'spacing.size.05'
  | 'spacing.size.06'
  | 'spacing.size.07'
  | 'spacing.size.08'
  | 'spacing.size.09'
  | 'spacing.padding.container'
  | 'spacing.padding.card'
  | 'spacing.gap.grid'
  | 'spacing.gap.gridLarge'
  | 'spacing.gap.gridMedium'
  | 'spacing.gap.gridSmall'
  | 'elevation.level.1'
  | 'elevation.level.2'
  | 'elevation.offset.y1'
  | 'elevation.offset.y2'
  | 'elevation.blur.sm'
  | 'elevation.blur.md'
  | 'elevation.spread.none'
  | 'elevation.depth'
  | 'elevation.default'
  | 'elevation.surface.raised'
  | 'elevation.surface.floating'
  | 'opacity.50'
  | 'opacity.100'
  | 'opacity.200'
  | 'opacity.300'
  | 'opacity.400'
  | 'opacity.500'
  | 'opacity.600'
  | 'opacity.700'
  | 'opacity.800'
  | 'opacity.900'
  | 'opacity.full'
  | 'opacity.disabled'
  | 'opacity.overlay'
  | 'dimension.breakpoint.sm'
  | 'dimension.breakpoint.md'
  | 'dimension.breakpoint.lg'
  | 'dimension.breakpoint.xl'
  | 'dimension.breakpoint.xxl'
  | 'dimension.breakpoint.xxxl'
  | 'dimension.tapTargetMin'
  | 'dimension.actionMinHeight'
  | 'dimension.minTarget'
  | 'dimension.buttonMinHeight'
  | 'shape.radius.none'
  | 'shape.radius.01'
  | 'shape.radius.02'
  | 'shape.radius.medium'
  | 'shape.radius.03'
  | 'shape.radius.04'
  | 'shape.radius.05'
  | 'shape.radius.full'
  | 'shape.radius.extraLarge'
  | 'shape.radius.large'
  | 'shape.radius.small'
  | 'shape.radius.extraSmall'
  | 'shape.radius.default'
  | 'shape.border.width.hairline'
  | 'shape.border.width.thick'
  | 'shape.border.style.solid'
  | 'shape.border.style.dashed'
  | 'shape.control.radius.default'
  | 'shape.control.radius.pill'
  | 'shape.control.border.defaultWidth'
  | 'shape.control.border.defaultStyle'
  | 'shape.control.border.focusWidth'
  | 'motion.duration.instant'
  | 'motion.duration.short1'
  | 'motion.duration.short2'
  | 'motion.duration.short3'
  | 'motion.duration.short'
  | 'motion.duration.medium'
  | 'motion.duration.medium1'
  | 'motion.duration.medium2'
  | 'motion.duration.medium3'
  | 'motion.duration.long'
  | 'motion.duration.long1'
  | 'motion.duration.long2'
  | 'motion.duration.long3'
  | 'motion.easing.standard'
  | 'motion.easing.emphasizedIn'
  | 'motion.easing.emphasizedOut'
  | 'motion.easing.quick.enter'
  | 'motion.easing.quick.exit'
  | 'motion.easing.soft.enter'
  | 'motion.easing.soft.exit'
  | 'motion.easing.continuous'
  | 'motion.easing.bounce'
  | 'motion.easing.linear'
  | 'motion.keyframes.fadeIn'
  | 'motion.keyframes.slideUp'
  | 'motion.keyframes.slideDown'
  | 'motion.keyframes.scaleIn'
  | 'motion.keyframes.pulse'
  | 'motion.delay.none'
  | 'motion.delay.short'
  | 'motion.delay.medium'
  | 'motion.delay.long'
  | 'motion.stagger.xs'
  | 'motion.stagger.sm'
  | 'motion.stagger.md'
  | 'motion.stagger.lg'
  | 'motion.stagger.list'
  | 'motion.stagger.card'
  | 'motion.stagger.section'
  | 'motion.interaction.press.duration'
  | 'motion.interaction.press.easing'
  | 'motion.interaction.press.scale'
  | 'motion.interaction.hover.duration'
  | 'motion.interaction.hover.easing'
  | 'motion.interaction.focus.duration'
  | 'motion.interaction.focus.easing'
  | 'motion.interaction.enter.duration'
  | 'motion.interaction.enter.easing'
  | 'motion.interaction.exit.duration'
  | 'motion.interaction.exit.easing'
  | 'motion.interaction.modal.enter.duration'
  | 'motion.interaction.modal.enter.easing'
  | 'motion.interaction.modal.exit.duration'
  | 'motion.interaction.modal.exit.easing'
  | 'motion.interaction.tooltip.enter.duration'
  | 'motion.interaction.tooltip.enter.easing'
  | 'motion.interaction.tooltip.enter.delay'
  | 'motion.interaction.tooltip.exit.duration'
  | 'motion.interaction.tooltip.exit.easing'
  | 'density.scale.compact'
  | 'density.scale.comfortable'
  | 'density.scale.spacious'
  | 'layer.base'
  | 'layer.dropdown'
  | 'layer.overlay'
  | 'layer.modal'
  | 'layer.toast'
  | 'layer.tooltip'
  | 'layout.container.sm'
  | 'layout.container.md'
  | 'layout.container.lg'
  | 'layout.container.xl'
  | 'layout.container.xxl'
  | 'icon.size.sm'
  | 'icon.size.md'
  | 'icon.size.lg'
  | 'icon.size.xl'
  | 'icon.strokeWidth.default'
  | 'effect.backdropBlur.sm'
  | 'effect.backdropBlur.md'
  | 'effect.backdropBlur.lg'
  | 'content.maxWidth.prose'
  | 'content.maxWidth.narrow'
  | 'content.maxWidth.wide'
  | 'content.maxWidth.article'
  | 'content.maxWidth.sidebar'
  | 'content.maxWidth.documentation'
  | 'content.measure.comfortable'
  | 'content.measure.compact'
  | 'content.spacing.paragraph'
  | 'content.spacing.section'
  | 'interaction.focus.ringWidth'
  | 'interaction.focus.ringOffset'
  | 'interaction.focus.ringOpacity'
  | 'interaction.press.scale'
  | 'interaction.press.duration'
  | 'interaction.disabled.opacity'
  | 'interaction.text.hover'
  | 'interaction.text.active'
  | 'interaction.text.disabled'
  | 'interaction.background.hover'
  | 'interaction.background.active'
  | 'interaction.background.selected'
  | 'interaction.background.disabled'
  | 'interaction.border.hover'
  | 'interaction.border.active'
  | 'interaction.border.disabled'
  | 'component.pagination.gap.x'
  | 'component.pagination.minSize'
  | 'component.pagination.gapX'
  | 'component.foreground'
  | 'component.typography.variation.wghtHeading'
  | 'component.typography.variation.wdthResponsive'
  | 'component.otp.field.gap'
  | 'component.otp.field.minWidth'
  | 'component.otp.field.height'
  | 'component.otp.field.fontSize'
  | 'component.otp.field.fontWeight'
  | 'component.otp.field.radius'
  | 'component.otp.color.text'
  | 'component.otp.color.bg'
  | 'component.otp.color.border'
  | 'component.otp.color.focus'
  | 'component.otp.fieldGap'
  | 'component.otp.fieldMinWidth'
  | 'component.otp.fieldHeight'
  | 'component.otp.fieldFontSize'
  | 'component.otp.fieldFontWeight'
  | 'component.otp.fieldRadius'
  | 'component.otp.colorText'
  | 'component.otp.colorBg'
  | 'component.otp.colorBorder'
  | 'component.test.dsSemanticColorBgPrimary'
  | 'component.test.customSemanticColorBgPrimary'
  | 'component.test.myCustomBg'
  | 'component.test.path'
  | 'component.test.typeWghtHeading'
  | 'component.test.typeWdthResponsive'
  | 'components.action.padding.composite.small'
  | 'components.action.padding.composite.default'
  | 'components.action.padding.composite.large'
  | 'components.action.padding.vertical.small'
  | 'components.action.padding.vertical.default'
  | 'components.action.padding.vertical.large'
  | 'components.action.padding.horizontal.small'
  | 'components.action.padding.horizontal.default'
  | 'components.action.padding.horizontal.large'
  | 'components.action.height.small'
  | 'components.action.height.default'
  | 'components.action.height.large'
  | 'components.action.radius.default'
  | 'components.action.radius.rounded'
  | 'components.action.radius.pill'
  | 'components.action.gap.icon'
  | 'components.action.gap.composite'
  | 'components.action.typography.fontWeight'
  | 'components.action.typography.fontSize.small'
  | 'components.action.typography.fontSize.default'
  | 'components.action.typography.fontSize.large'
  | 'components.input.padding.composite.small'
  | 'components.input.padding.composite.default'
  | 'components.input.padding.composite.large'
  | 'components.input.padding.vertical.small'
  | 'components.input.padding.vertical.default'
  | 'components.input.padding.vertical.large'
  | 'components.input.padding.horizontal.small'
  | 'components.input.padding.horizontal.default'
  | 'components.input.padding.horizontal.large'
  | 'components.input.height.small'
  | 'components.input.height.default'
  | 'components.input.height.large'
  | 'components.input.radius.default'
  | 'components.input.radius.rounded'
  | 'components.input.border.width.default'
  | 'components.input.border.width.focus'
  | 'components.input.gap.icon'
  | 'components.input.gap.label'
  | 'components.input.gap.help'
  | 'components.input.typography.fontSize.small'
  | 'components.input.typography.fontSize.default'
  | 'components.input.typography.fontSize.large'
  | 'components.input.typography.fontWeight'
  | 'components.navigation.padding.composite.default'
  | 'components.navigation.padding.composite.compact'
  | 'components.navigation.padding.item.vertical'
  | 'components.navigation.padding.item.horizontal'
  | 'components.navigation.gap.items'
  | 'components.navigation.gap.icon'
  | 'components.navigation.height.bar'
  | 'components.navigation.height.item'
  | 'components.feedback.padding.composite.default'
  | 'components.feedback.padding.composite.compact'
  | 'components.feedback.gap.icon'
  | 'components.feedback.gap.action'
  | 'components.feedback.radius.default'
  | 'components.feedback.border.width'
  | 'control.size.sm.height'
  | 'control.size.sm.paddingX'
  | 'control.size.sm.paddingY'
  | 'control.size.md.height'
  | 'control.size.md.paddingX'
  | 'control.size.md.paddingY'
  | 'control.size.lg.height'
  | 'control.size.lg.paddingX'
  | 'control.size.lg.paddingY'
  | 'link.text'
  | 'link.decorationColor'
  | 'link.decorationThickness'
  | 'link.decorationOffset'
  | 'link.hover.text'
  | 'link.visited.text'
  | 'skeleton.background'
  | 'skeleton.foreground'
  | 'skeleton.shineDuration'
  | 'datavis.onFill.default'
  | 'datavis.onFill.muted'
  | 'datavis.gridline.major'
  | 'datavis.gridline.minor'
  | 'datavis.strokeWidth.series'
  | 'datavis.strokeWidth.grid'
  | 'focus.ring'
  | 'focus.ringOffset'
  | 'overlay.scrimWeak'
  | 'overlay.scrimMedium'
  | 'overlay.scrimStrong';

/**
 * color token paths
 */
export type ColorTokenPath =
  | 'color.mode.black'
  | 'color.mode.white'
  | 'color.mode.light'
  | 'color.mode.dark'
  | 'color.mode.transparent'
  | 'color.palette.brand.primary.100'
  | 'color.palette.brand.primary.200'
  | 'color.palette.brand.primary.300'
  | 'color.palette.brand.primary.400'
  | 'color.palette.brand.primary.500'
  | 'color.palette.brand.primary.600'
  | 'color.palette.brand.primary.700'
  | 'color.palette.brand.primary.800'
  | 'color.palette.neutral.100'
  | 'color.palette.neutral.200'
  | 'color.palette.neutral.300'
  | 'color.palette.neutral.400'
  | 'color.palette.neutral.500'
  | 'color.palette.neutral.600'
  | 'color.palette.neutral.700'
  | 'color.palette.neutral.800'
  | 'color.palette.red.100'
  | 'color.palette.red.200'
  | 'color.palette.red.300'
  | 'color.palette.red.400'
  | 'color.palette.red.500'
  | 'color.palette.red.600'
  | 'color.palette.red.700'
  | 'color.palette.red.800'
  | 'color.palette.orange.100'
  | 'color.palette.orange.200'
  | 'color.palette.orange.300'
  | 'color.palette.orange.400'
  | 'color.palette.orange.500'
  | 'color.palette.orange.600'
  | 'color.palette.orange.700'
  | 'color.palette.orange.800'
  | 'color.palette.yellow.100'
  | 'color.palette.yellow.200'
  | 'color.palette.yellow.300'
  | 'color.palette.yellow.400'
  | 'color.palette.yellow.500'
  | 'color.palette.yellow.600'
  | 'color.palette.yellow.700'
  | 'color.palette.yellow.800'
  | 'color.palette.green.100'
  | 'color.palette.green.200'
  | 'color.palette.green.300'
  | 'color.palette.green.400'
  | 'color.palette.green.500'
  | 'color.palette.green.600'
  | 'color.palette.green.700'
  | 'color.palette.green.800'
  | 'color.palette.blue.100'
  | 'color.palette.blue.200'
  | 'color.palette.blue.300'
  | 'color.palette.blue.400'
  | 'color.palette.blue.500'
  | 'color.palette.blue.600'
  | 'color.palette.blue.700'
  | 'color.palette.blue.800'
  | 'color.palette.teal.100'
  | 'color.palette.teal.200'
  | 'color.palette.teal.300'
  | 'color.palette.teal.400'
  | 'color.palette.teal.500'
  | 'color.palette.teal.600'
  | 'color.palette.teal.700'
  | 'color.palette.teal.800'
  | 'color.palette.violet.100'
  | 'color.palette.violet.200'
  | 'color.palette.violet.300'
  | 'color.palette.violet.400'
  | 'color.palette.violet.500'
  | 'color.palette.violet.600'
  | 'color.palette.violet.700'
  | 'color.palette.violet.800'
  | 'color.datavis.viridis.1'
  | 'color.datavis.viridis.2'
  | 'color.datavis.viridis.3'
  | 'color.datavis.viridis.4'
  | 'color.datavis.viridis.5'
  | 'color.datavis.viridis.6'
  | 'color.datavis.viridis.7'
  | 'color.datavis.viridis.8'
  | 'color.datavis.viridis.9'
  | 'color.datavis.viridis.10'
  | 'color.datavis.magma.1'
  | 'color.datavis.magma.2'
  | 'color.datavis.magma.3'
  | 'color.datavis.magma.4'
  | 'color.datavis.magma.5'
  | 'color.datavis.magma.6'
  | 'color.datavis.magma.7'
  | 'color.datavis.magma.8'
  | 'color.datavis.magma.9'
  | 'color.datavis.magma.10'
  | 'color.datavis.plasma.1'
  | 'color.datavis.plasma.2'
  | 'color.datavis.plasma.3'
  | 'color.datavis.plasma.4'
  | 'color.datavis.plasma.5'
  | 'color.datavis.plasma.6'
  | 'color.datavis.plasma.7'
  | 'color.datavis.plasma.8'
  | 'color.datavis.plasma.9'
  | 'color.datavis.plasma.10'
  | 'color.datavis.inferno.1'
  | 'color.datavis.inferno.2'
  | 'color.datavis.inferno.3'
  | 'color.datavis.inferno.4'
  | 'color.datavis.inferno.5'
  | 'color.datavis.inferno.6'
  | 'color.datavis.inferno.7'
  | 'color.datavis.inferno.8'
  | 'color.datavis.inferno.9'
  | 'color.datavis.inferno.10'
  | 'color.datavis.cividis.1'
  | 'color.datavis.cividis.2'
  | 'color.datavis.cividis.3'
  | 'color.datavis.cividis.4'
  | 'color.datavis.cividis.5'
  | 'color.datavis.cividis.6'
  | 'color.datavis.cividis.7'
  | 'color.datavis.cividis.8'
  | 'color.datavis.cividis.9'
  | 'color.datavis.cividis.10'
  | 'color.datavis.categorical.1'
  | 'color.datavis.categorical.2'
  | 'color.datavis.categorical.3'
  | 'color.datavis.categorical.4'
  | 'color.datavis.categorical.5'
  | 'color.datavis.categorical.6'
  | 'color.datavis.categorical.7'
  | 'color.datavis.categorical.8'
  | 'color.datavis.divergent.neg'
  | 'color.datavis.divergent.neu'
  | 'color.datavis.divergent.pos'
  | 'color.gradient.brandPrimary'
  | 'color.gradient.brand.primary'
  | 'color.overlay.scrim'
  | 'color.opacity.50'
  | 'color.selection.background'
  | 'color.selection.foreground'
  | 'color.foreground.primary'
  | 'color.foreground.secondary'
  | 'color.foreground.tertiary'
  | 'color.foreground.accent'
  | 'color.foreground.danger'
  | 'color.foreground.hover'
  | 'color.foreground.link'
  | 'color.foreground.linkHover'
  | 'color.foreground.linkVisited'
  | 'color.foreground.onBrand'
  | 'color.foreground.info'
  | 'color.foreground.success'
  | 'color.foreground.warning'
  | 'color.foreground.onDangerSubtle'
  | 'color.foreground.onInfoSubtle'
  | 'color.foreground.onSuccessSubtle'
  | 'color.foreground.onWarningSubtle'
  | 'color.foreground.highlight'
  | 'color.foreground.disabled'
  | 'color.foreground.placeholder'
  | 'color.foreground.inverse'
  | 'color.background.primary'
  | 'color.background.secondary'
  | 'color.background.tertiary'
  | 'color.background.highlight'
  | 'color.background.accent'
  | 'color.background.hover'
  | 'color.background.dangerStrong'
  | 'color.background.dangerSubtle'
  | 'color.background.elevated'
  | 'color.background.brand'
  | 'color.background.imageOverlay'
  | 'color.background.infoStrong'
  | 'color.background.infoSubtle'
  | 'color.background.successStrong'
  | 'color.background.successSubtle'
  | 'color.background.warningStrong'
  | 'color.background.warningSubtle'
  | 'color.background.active'
  | 'color.background.disabled'
  | 'color.background.placeholder'
  | 'color.background.readOnly'
  | 'color.background.inverse'
  | 'color.border.default'
  | 'color.border.subtle'
  | 'color.border.bold'
  | 'color.border.disabled'
  | 'color.border.light'
  | 'color.border.primary'
  | 'color.border.hover'
  | 'color.border.accent'
  | 'color.border.focus'
  | 'color.border.danger'
  | 'color.border.info'
  | 'color.border.onColor'
  | 'color.border.success'
  | 'color.border.warning'
  | 'color.border.strong'
  | 'color.status.info'
  | 'color.status.success'
  | 'color.status.warning'
  | 'color.status.danger'
  | 'color.status.highlight'
  | 'color.data.trend.default'
  | 'color.data.trend.up'
  | 'color.data.trend.down'
  | 'color.data.trend.neutral'
  | 'color.action.background.primary.default'
  | 'color.action.background.primary.hover'
  | 'color.action.background.primary.active'
  | 'color.action.background.primary.disabled'
  | 'color.action.background.secondary.default'
  | 'color.action.background.secondary.hover'
  | 'color.action.background.secondary.active'
  | 'color.action.background.danger.default'
  | 'color.action.background.danger.hover'
  | 'color.action.background.danger.active'
  | 'color.action.foreground.primary.default'
  | 'color.action.foreground.primary.disabled'
  | 'color.action.foreground.secondary.default'
  | 'color.action.foreground.danger.default'
  | 'color.action.border.primary.default'
  | 'color.action.border.primary.focus'
  | 'color.action.border.secondary.default'
  | 'color.action.border.secondary.hover'
  | 'color.action.border.danger.default'
  | 'color.feedback.background.success.strong'
  | 'color.feedback.background.success.subtle'
  | 'color.feedback.background.warning.strong'
  | 'color.feedback.background.warning.subtle'
  | 'color.feedback.background.danger.strong'
  | 'color.feedback.background.danger.subtle'
  | 'color.feedback.background.info.strong'
  | 'color.feedback.background.info.subtle'
  | 'color.feedback.foreground.success.default'
  | 'color.feedback.foreground.success.onSubtle'
  | 'color.feedback.foreground.warning.default'
  | 'color.feedback.foreground.warning.onSubtle'
  | 'color.feedback.foreground.danger.default'
  | 'color.feedback.foreground.danger.onSubtle'
  | 'color.feedback.foreground.info.default'
  | 'color.feedback.foreground.info.onSubtle'
  | 'color.feedback.border.success'
  | 'color.feedback.border.warning'
  | 'color.feedback.border.danger'
  | 'color.feedback.border.info'
  | 'color.navigation.background.primary'
  | 'color.navigation.background.secondary'
  | 'color.navigation.foreground.primary'
  | 'color.navigation.foreground.secondary'
  | 'color.navigation.foreground.active'
  | 'color.navigation.foreground.hover'
  | 'color.navigation.border.primary'
  | 'color.syntax.plain'
  | 'color.syntax.comment.color'
  | 'color.syntax.keyword'
  | 'color.syntax.definition'
  | 'color.syntax.punctuation'
  | 'color.syntax.property'
  | 'color.syntax.tag'
  | 'color.syntax.static'
  | 'color.syntax.string';

/**
 * typography token paths
 */
export type TypographyTokenPath =
  | 'typography.fontFamily.sans'
  | 'typography.fontFamily.serif'
  | 'typography.fontFamily.mono'
  | 'typography.fontFamily.inter'
  | 'typography.fontFamily.newsreader'
  | 'typography.fontFamily.monaspace'
  | 'typography.weight.thin'
  | 'typography.weight.light'
  | 'typography.weight.regular'
  | 'typography.weight.medium'
  | 'typography.weight.bold'
  | 'typography.weight.black'
  | 'typography.ramp.1'
  | 'typography.ramp.2'
  | 'typography.ramp.3'
  | 'typography.ramp.4'
  | 'typography.ramp.5'
  | 'typography.ramp.6'
  | 'typography.ramp.7'
  | 'typography.ramp.8'
  | 'typography.ramp.9'
  | 'typography.ramp.10'
  | 'typography.ramp.11'
  | 'typography.ramp.12'
  | 'typography.ramp.13'
  | 'typography.ramp.14'
  | 'typography.ramp.15'
  | 'typography.ramp.16'
  | 'typography.lineHeight.tight'
  | 'typography.lineHeight.normal'
  | 'typography.lineHeight.loose'
  | 'typography.lineHeight.body'
  | 'typography.lineHeight.collapse'
  | 'typography.lineHeight.heading'
  | 'typography.letterSpacing.tight'
  | 'typography.letterSpacing.normal'
  | 'typography.letterSpacing.wide'
  | 'typography.features.tabularNums'
  | 'typography.features.liningNums'
  | 'typography.semanticFamily.heading'
  | 'typography.semanticFamily.body'
  | 'typography.semanticFamily.mono'
  | 'typography.semanticFamily.serif'
  | 'typography.body.01'
  | 'typography.body.02'
  | 'typography.body.03'
  | 'typography.body.04'
  | 'typography.body.default.fontFamily'
  | 'typography.body.default.fontWeight'
  | 'typography.body.default.fontSize'
  | 'typography.body.default.lineHeight'
  | 'typography.body.default.letterSpacing'
  | 'typography.body.small.fontFamily'
  | 'typography.body.small.fontWeight'
  | 'typography.body.small.fontSize'
  | 'typography.body.small.lineHeight'
  | 'typography.button.01'
  | 'typography.button.02'
  | 'typography.button.03'
  | 'typography.caption.01'
  | 'typography.caption.02'
  | 'typography.caption.03'
  | 'typography.fontWeight.black'
  | 'typography.fontWeight.bold'
  | 'typography.fontWeight.light'
  | 'typography.fontWeight.medium'
  | 'typography.fontWeight.regular'
  | 'typography.heading.01'
  | 'typography.heading.02'
  | 'typography.heading.03'
  | 'typography.heading.04'
  | 'typography.heading.05'
  | 'typography.heading.06'
  | 'typography.oversize.01'
  | 'typography.oversize.02'
  | 'typography.oversize.03'
  | 'typography.oversize.04'
  | 'typography.meta.caption.fontFamily'
  | 'typography.meta.caption.fontWeight'
  | 'typography.meta.caption.fontSize'
  | 'typography.meta.caption.lineHeight'
  | 'typography.meta.legal.fontFamily'
  | 'typography.meta.legal.fontWeight'
  | 'typography.meta.legal.fontSize'
  | 'typography.meta.legal.lineHeight';

/**
 * scale token paths
 */
export type ScaleTokenPath =
  | 'scale.100'
  | 'scale.110'
  | 'scale.125'
  | 'scale.150'
  | 'scale.175'
  | 'scale.200'
  | 'scale.225'
  | 'scale.250'
  | 'scale.275'
  | 'scale.300'
  | 'scale.base'
  | 'scale.050'
  | 'scale.000';

/**
 * spacing token paths
 */
export type SpacingTokenPath =
  | 'spacing.size.10'
  | 'spacing.size.00'
  | 'spacing.size.01'
  | 'spacing.size.02'
  | 'spacing.size.03'
  | 'spacing.size.04'
  | 'spacing.size.05'
  | 'spacing.size.06'
  | 'spacing.size.07'
  | 'spacing.size.08'
  | 'spacing.size.09'
  | 'spacing.padding.container'
  | 'spacing.padding.card'
  | 'spacing.gap.grid'
  | 'spacing.gap.gridLarge'
  | 'spacing.gap.gridMedium'
  | 'spacing.gap.gridSmall';

/**
 * elevation token paths
 */
export type ElevationTokenPath =
  | 'elevation.level.1'
  | 'elevation.level.2'
  | 'elevation.offset.y1'
  | 'elevation.offset.y2'
  | 'elevation.blur.sm'
  | 'elevation.blur.md'
  | 'elevation.spread.none'
  | 'elevation.depth'
  | 'elevation.default'
  | 'elevation.surface.raised'
  | 'elevation.surface.floating';

/**
 * opacity token paths
 */
export type OpacityTokenPath =
  | 'opacity.50'
  | 'opacity.100'
  | 'opacity.200'
  | 'opacity.300'
  | 'opacity.400'
  | 'opacity.500'
  | 'opacity.600'
  | 'opacity.700'
  | 'opacity.800'
  | 'opacity.900'
  | 'opacity.full'
  | 'opacity.disabled'
  | 'opacity.overlay';

/**
 * dimension token paths
 */
export type DimensionTokenPath =
  | 'dimension.breakpoint.sm'
  | 'dimension.breakpoint.md'
  | 'dimension.breakpoint.lg'
  | 'dimension.breakpoint.xl'
  | 'dimension.breakpoint.xxl'
  | 'dimension.breakpoint.xxxl'
  | 'dimension.tapTargetMin'
  | 'dimension.actionMinHeight'
  | 'dimension.minTarget'
  | 'dimension.buttonMinHeight';

/**
 * shape token paths
 */
export type ShapeTokenPath =
  | 'shape.radius.none'
  | 'shape.radius.01'
  | 'shape.radius.02'
  | 'shape.radius.medium'
  | 'shape.radius.03'
  | 'shape.radius.04'
  | 'shape.radius.05'
  | 'shape.radius.full'
  | 'shape.radius.extraLarge'
  | 'shape.radius.large'
  | 'shape.radius.small'
  | 'shape.radius.extraSmall'
  | 'shape.radius.default'
  | 'shape.border.width.hairline'
  | 'shape.border.width.thick'
  | 'shape.border.style.solid'
  | 'shape.border.style.dashed'
  | 'shape.control.radius.default'
  | 'shape.control.radius.pill'
  | 'shape.control.border.defaultWidth'
  | 'shape.control.border.defaultStyle'
  | 'shape.control.border.focusWidth';

/**
 * motion token paths
 */
export type MotionTokenPath =
  | 'motion.duration.instant'
  | 'motion.duration.short1'
  | 'motion.duration.short2'
  | 'motion.duration.short3'
  | 'motion.duration.short'
  | 'motion.duration.medium'
  | 'motion.duration.medium1'
  | 'motion.duration.medium2'
  | 'motion.duration.medium3'
  | 'motion.duration.long'
  | 'motion.duration.long1'
  | 'motion.duration.long2'
  | 'motion.duration.long3'
  | 'motion.easing.standard'
  | 'motion.easing.emphasizedIn'
  | 'motion.easing.emphasizedOut'
  | 'motion.easing.quick.enter'
  | 'motion.easing.quick.exit'
  | 'motion.easing.soft.enter'
  | 'motion.easing.soft.exit'
  | 'motion.easing.continuous'
  | 'motion.easing.bounce'
  | 'motion.easing.linear'
  | 'motion.keyframes.fadeIn'
  | 'motion.keyframes.slideUp'
  | 'motion.keyframes.slideDown'
  | 'motion.keyframes.scaleIn'
  | 'motion.keyframes.pulse'
  | 'motion.delay.none'
  | 'motion.delay.short'
  | 'motion.delay.medium'
  | 'motion.delay.long'
  | 'motion.stagger.xs'
  | 'motion.stagger.sm'
  | 'motion.stagger.md'
  | 'motion.stagger.lg'
  | 'motion.stagger.list'
  | 'motion.stagger.card'
  | 'motion.stagger.section'
  | 'motion.interaction.press.duration'
  | 'motion.interaction.press.easing'
  | 'motion.interaction.press.scale'
  | 'motion.interaction.hover.duration'
  | 'motion.interaction.hover.easing'
  | 'motion.interaction.focus.duration'
  | 'motion.interaction.focus.easing'
  | 'motion.interaction.enter.duration'
  | 'motion.interaction.enter.easing'
  | 'motion.interaction.exit.duration'
  | 'motion.interaction.exit.easing'
  | 'motion.interaction.modal.enter.duration'
  | 'motion.interaction.modal.enter.easing'
  | 'motion.interaction.modal.exit.duration'
  | 'motion.interaction.modal.exit.easing'
  | 'motion.interaction.tooltip.enter.duration'
  | 'motion.interaction.tooltip.enter.easing'
  | 'motion.interaction.tooltip.enter.delay'
  | 'motion.interaction.tooltip.exit.duration'
  | 'motion.interaction.tooltip.exit.easing';

/**
 * density token paths
 */
export type DensityTokenPath =
  | 'density.scale.compact'
  | 'density.scale.comfortable'
  | 'density.scale.spacious';

/**
 * layer token paths
 */
export type LayerTokenPath =
  | 'layer.base'
  | 'layer.dropdown'
  | 'layer.overlay'
  | 'layer.modal'
  | 'layer.toast'
  | 'layer.tooltip';

/**
 * layout token paths
 */
export type LayoutTokenPath =
  | 'layout.container.sm'
  | 'layout.container.md'
  | 'layout.container.lg'
  | 'layout.container.xl'
  | 'layout.container.xxl';

/**
 * icon token paths
 */
export type IconTokenPath =
  | 'icon.size.sm'
  | 'icon.size.md'
  | 'icon.size.lg'
  | 'icon.size.xl'
  | 'icon.strokeWidth.default';

/**
 * effect token paths
 */
export type EffectTokenPath =
  | 'effect.backdropBlur.sm'
  | 'effect.backdropBlur.md'
  | 'effect.backdropBlur.lg';

/**
 * content token paths
 */
export type ContentTokenPath =
  | 'content.maxWidth.prose'
  | 'content.maxWidth.narrow'
  | 'content.maxWidth.wide'
  | 'content.maxWidth.article'
  | 'content.maxWidth.sidebar'
  | 'content.maxWidth.documentation'
  | 'content.measure.comfortable'
  | 'content.measure.compact'
  | 'content.spacing.paragraph'
  | 'content.spacing.section';

/**
 * interaction token paths
 */
export type InteractionTokenPath =
  | 'interaction.focus.ringWidth'
  | 'interaction.focus.ringOffset'
  | 'interaction.focus.ringOpacity'
  | 'interaction.press.scale'
  | 'interaction.press.duration'
  | 'interaction.disabled.opacity'
  | 'interaction.text.hover'
  | 'interaction.text.active'
  | 'interaction.text.disabled'
  | 'interaction.background.hover'
  | 'interaction.background.active'
  | 'interaction.background.selected'
  | 'interaction.background.disabled'
  | 'interaction.border.hover'
  | 'interaction.border.active'
  | 'interaction.border.disabled';

/**
 * component token paths
 */
export type ComponentTokenPath =
  | 'component.pagination.gap.x'
  | 'component.pagination.minSize'
  | 'component.pagination.gapX'
  | 'component.foreground'
  | 'component.typography.variation.wghtHeading'
  | 'component.typography.variation.wdthResponsive'
  | 'component.otp.field.gap'
  | 'component.otp.field.minWidth'
  | 'component.otp.field.height'
  | 'component.otp.field.fontSize'
  | 'component.otp.field.fontWeight'
  | 'component.otp.field.radius'
  | 'component.otp.color.text'
  | 'component.otp.color.bg'
  | 'component.otp.color.border'
  | 'component.otp.color.focus'
  | 'component.otp.fieldGap'
  | 'component.otp.fieldMinWidth'
  | 'component.otp.fieldHeight'
  | 'component.otp.fieldFontSize'
  | 'component.otp.fieldFontWeight'
  | 'component.otp.fieldRadius'
  | 'component.otp.colorText'
  | 'component.otp.colorBg'
  | 'component.otp.colorBorder'
  | 'component.test.dsSemanticColorBgPrimary'
  | 'component.test.customSemanticColorBgPrimary'
  | 'component.test.myCustomBg'
  | 'component.test.path'
  | 'component.test.typeWghtHeading'
  | 'component.test.typeWdthResponsive';

/**
 * components token paths
 */
export type ComponentsTokenPath =
  | 'components.action.padding.composite.small'
  | 'components.action.padding.composite.default'
  | 'components.action.padding.composite.large'
  | 'components.action.padding.vertical.small'
  | 'components.action.padding.vertical.default'
  | 'components.action.padding.vertical.large'
  | 'components.action.padding.horizontal.small'
  | 'components.action.padding.horizontal.default'
  | 'components.action.padding.horizontal.large'
  | 'components.action.height.small'
  | 'components.action.height.default'
  | 'components.action.height.large'
  | 'components.action.radius.default'
  | 'components.action.radius.rounded'
  | 'components.action.radius.pill'
  | 'components.action.gap.icon'
  | 'components.action.gap.composite'
  | 'components.action.typography.fontWeight'
  | 'components.action.typography.fontSize.small'
  | 'components.action.typography.fontSize.default'
  | 'components.action.typography.fontSize.large'
  | 'components.input.padding.composite.small'
  | 'components.input.padding.composite.default'
  | 'components.input.padding.composite.large'
  | 'components.input.padding.vertical.small'
  | 'components.input.padding.vertical.default'
  | 'components.input.padding.vertical.large'
  | 'components.input.padding.horizontal.small'
  | 'components.input.padding.horizontal.default'
  | 'components.input.padding.horizontal.large'
  | 'components.input.height.small'
  | 'components.input.height.default'
  | 'components.input.height.large'
  | 'components.input.radius.default'
  | 'components.input.radius.rounded'
  | 'components.input.border.width.default'
  | 'components.input.border.width.focus'
  | 'components.input.gap.icon'
  | 'components.input.gap.label'
  | 'components.input.gap.help'
  | 'components.input.typography.fontSize.small'
  | 'components.input.typography.fontSize.default'
  | 'components.input.typography.fontSize.large'
  | 'components.input.typography.fontWeight'
  | 'components.navigation.padding.composite.default'
  | 'components.navigation.padding.composite.compact'
  | 'components.navigation.padding.item.vertical'
  | 'components.navigation.padding.item.horizontal'
  | 'components.navigation.gap.items'
  | 'components.navigation.gap.icon'
  | 'components.navigation.height.bar'
  | 'components.navigation.height.item'
  | 'components.feedback.padding.composite.default'
  | 'components.feedback.padding.composite.compact'
  | 'components.feedback.gap.icon'
  | 'components.feedback.gap.action'
  | 'components.feedback.radius.default'
  | 'components.feedback.border.width';

/**
 * control token paths
 */
export type ControlTokenPath =
  | 'control.size.sm.height'
  | 'control.size.sm.paddingX'
  | 'control.size.sm.paddingY'
  | 'control.size.md.height'
  | 'control.size.md.paddingX'
  | 'control.size.md.paddingY'
  | 'control.size.lg.height'
  | 'control.size.lg.paddingX'
  | 'control.size.lg.paddingY';

/**
 * link token paths
 */
export type LinkTokenPath =
  | 'link.text'
  | 'link.decorationColor'
  | 'link.decorationThickness'
  | 'link.decorationOffset'
  | 'link.hover.text'
  | 'link.visited.text';

/**
 * skeleton token paths
 */
export type SkeletonTokenPath =
  | 'skeleton.background'
  | 'skeleton.foreground'
  | 'skeleton.shineDuration';

/**
 * datavis token paths
 */
export type DatavisTokenPath =
  | 'datavis.onFill.default'
  | 'datavis.onFill.muted'
  | 'datavis.gridline.major'
  | 'datavis.gridline.minor'
  | 'datavis.strokeWidth.series'
  | 'datavis.strokeWidth.grid';

/**
 * focus token paths
 */
export type FocusTokenPath =
  | 'focus.ring'
  | 'focus.ringOffset';

/**
 * overlay token paths
 */
export type OverlayTokenPath =
  | 'overlay.scrimWeak'
  | 'overlay.scrimMedium'
  | 'overlay.scrimStrong';

/**
 * Token reference string (with curly braces)
 */
export type TokenReference = `{${TokenPath}}`;

/**
 * CSS Custom Property name
 */
export type CSSVariableName = `--${string}`;

/**
 * Helper type for token resolution functions
 */
export interface TokenResolver {
  resolve: (path: TokenPath) => string;
  toCSSVar: (path: TokenPath) => CSSVariableName;
  reference: (path: TokenPath) => TokenReference;
}

/**
 * Token metadata structure
 */
export interface TokenMetadata {
  $value: unknown;
  $type?: string;
  $description?: string;
}

/**
 * Token group structure
 */
export interface TokenGroup {
  [key: string]: TokenMetadata | TokenGroup;
}

/**
 * Usage Examples:
 * 
 * ```typescript
 * import type { TokenPath, CoreTokenPath } from "@/types/designTokens";
 * 
 * // Type-safe token references
 * const primaryColor: TokenPath = "core.color.blue.500";
 * const semanticBg: TokenPath = "semantic.color.background.primary";
 * 
 * // In token resolution functions
 * function resolveToken(path: TokenPath): string {
 *   // implementation...
 * }
 * ```
 */
